### ISSUE TITLE
Source is incomplete

### ISSUE THREAD

**Issue by jpotier** [jeantil/admission_post_bac#1]
https://gist.github.com/Benoitlecorre/30b76f7fda430d4a06063a7cfc5e3844 is more up-to-date (although it has typos)

**Comment by jeantil** [comment]
I can't really compare the whole thing but both are about 400 lines long so the code in the repo shouldn't be too incomplete. A far as I can tell this repo is now more complete than benoit's version. 

I know there are typos left in this repo though

**Comment by jpotier** [comment]
I've re-read through the whole PDF and fixed numerous typos, now I'm convinced the source is complete (although some typos may remain)

**Comment by jeantil** [comment]
thanks for the review
