### ISSUE TITLE
Conteneuriser l'application ?

### ISSUE THREAD

**Issue by w3st3ry** [jeantil/admission_post_bac#10]
Bonjour à tous,

Ayant moi même eu à faire face à l'instabilité de ce code il y a deux ans je propose de conteneuriser cette application pour éviter toute implosion de la machine de test.

Je recommande la technologie de pointe [Marcel Docker](https://github.com/brouberol/marcel) pour faire face à ce genre d'insectes.

Merci d'avance.

**Comment by inattendu** [comment]
Même pas peur, je le tente sans Docker marcel ou pas.

**Comment by w3st3ry** [comment]
D'après les rumeurs ce code est fait pour être fonctionnel uniquement sous l'OS Souverain.

Si quelqu'un aurait à disposition l'image, je suis preneur.

**Comment by motet-a** [comment]
@w3st3ry Avez-vous essayé d’envoyer un courrier reccommandé au Ministère de l’Éducation Nationale pour obtenir l’image Marcel en question ?

**Comment by w3st3ry** [comment]
@motet-a Négatif, les services de l'État français étant en pleine digitalisation et transition numérique (la preuve, du code sur un pdf) je pense utiliser un courriel pour une telle demande.

**Comment by brouberol** [comment]
Merci de promouvoir des technologies aussi sures que patriotes. Nous sommes fiers de vous.

**Comment by jpotier** [comment]
Bon, ça en est où l'OS souverrain ? Faut se r'trousser les manches et y mettre un bon coup de pétoire pour que ça avance-t-y ?

**Comment by charlycoste** [comment]
Sait-on quelle version d'Oracle est utilisée ? Je crois qu'il existe des VMs pour développeur sur leur site.
