### ISSUE TITLE
erreur copie

### ISSUE THREAD

**Issue by depfryer** [jeantil/admission_post_bac#13]
heu ligne 268 sa serais pas plutot "X: = 06" ??

**Comment by ch0c4** [comment]
Non c'est bien 61, regarde page 10 dans le pdf ou ligne 256 du gist https://gist.github.com/Benoitlecorre/30b76f7fda430d4a06063a7cfc5e3844#file-algo_apb_proper-sql-L256

**Comment by jpotier** [comment]
Je clos, merci pour la réponse @ch0c4. Hésitez pas à ouvrir des issues si jamais vous trouvez des coquilles.
