### ISSUE TITLE
Fichier des variables pas si vrai ?

### ISSUE THREAD

**Issue by AxelVoitier** [jeantil/admission_post_bac#18]
D'apres le fichier des variables, g_ti_cod correspondrait a code confidentiel inscription.

On pourrait l'extrapole au parametre en entree o_g_ti_cod.
Hors, a la lecture du code, ce parametre ne semble pas etre utilise comme un code confidentiel. Il est souvent utilise comme une cle de jointure.

Et puis il y'a ca lignes 290-292 :

``` sql
      ||'Erreur traitement d''un candidat AC pour l''étab'
      || o_g_ea_cod_ins ||' et la formation '|| o_g_ti_cod||':'|| o_c_gp_cod ||', le candidat'||c_rec.g_cn_cod
      ||' et le groupe : '||o_c_gp_cod||', rg :'||i;
```

Donc (o_)g_ti_cod correspondrait plus a un code formation.

**Comment by Skrol29** [comment]
Effectivement.

**Comment by inattendu** [comment]
Si on en crois le pastebin source ; le "fichier de variable" est effectivement à prendre avec des pincettes puis ce qu'il s'agit vraisemblablement des variables utilisées par l'appli de test d'APB dispo ici : http://www.simulation-apb.fr/.

Initialement il n'y a aucun lien entre le "fichier de variable" et l'algo PLSQL publié récemment par l'EN.
Cependant, un croisement peut nous aider dans la compréhension de l'algo.

**Comment by khena** [comment]
N'hésitez pas à faire des PR pour signaler les erreurs, le fichier n'est ni complet ni correct (et ouvert à débat). Je suis d'accord pour le code formation, je corrige le fichier.
