### ISSUE TITLE
Explication du code morceau par morceau

### ISSUE THREAD

**Issue by jferard** [jeantil/admission_post_bac#23]
Je propose de réaliser une explication détaillé du code, morceau par morceau, afin de pointer clairement ce qui pose problème et ce qui manque. Le nommage pourrait être "apb_ll4-20.sql" pour les paramètres de la fonction `gen_class_alea_V1_relatif_grp`, etc. Dans le fichier :
1. une reproduction du code
2. une mise en forme si nécessaire (pour arriver à un PL/SQL plus intuitif (par ex. les deux `CURSOR ... IS` seraient plus clairs avec un `LEFT JOIN` et sans `UNION`)
3. Une explication détaillée du fonctionnement du bout de code.

**Comment by piwai** [comment]
Pour la mise en forme, à partir du moment où on fait des changements autre que des simples typos ou de l'ajout de commentaires, il y a quand même un risque réel de modifier le comportement de l'algo sans s'en rendre compte, donc ca me parait très risqué.
Pour faire ça, idéalement il faudrait réussir à lancer la procédure avec un jeu de données pour faire des tests de non-régression par rapport à l'algo "de référence" qui a été fourni. Et encore, même avec des tests il faudrait être sur de couvrir suffisament de cas.

**Comment by jferard** [comment]
Evidemment, pas de mise en forme sur le fichier "abp.sql", mais sur des fichiers dérivés. Le but serait : 1) pédagogique ; 2) de mieux voir ce qui pose problème (informations manquantes, etc.). Ce n'est pas non plus essentiel, mais plutôt à voir comme une traduction. Pour l'explication détaillée, voir https://gist.github.com/jferard/d4dfcf283233a9aee68a69866be6f52b pour un exemple (c'est loin d'être l'essentiel de la fonction).

**Comment by khena** [comment]
Le code peut se découper de la manière suivant :
- les deux premières requetes, découpées chacune en 2 sous - requêtes
- chaque X correspond à une étape que nous pouvons expliquer.
- le refactoring permettrait effectivement une meilleure lecture du code (en particulier les jointures) mais doit être soumis à la relecture avant toute chose. Nous pouvons faire un fichier par partie.

**Comment by jferard** [comment]
Je travaille sur un fork en vue d'éventuelles pull request : https://github.com/jferard/admission_post_bac.git. Pour l'instant, c'est un peu brouillon, parce que ça avance un peu de tous les côtés en même temps.

**Comment by jferard** [comment]
C'est (pour l'instant) terminé, cf. https://github.com/jferard/admission_post_bac/tree/explications/src. Pas d'autre conclusion que ce qu'on savait déjà : le code est largement incomplet, avec quatre appels de fonctions inconnues et probablement d'autres fonctions qui sont appelées dans le traitement _complet_.

**Comment by khena** [comment]
Super @jferard je m'apprêtais à faire ça ce soir justement ! On rapatrie tout ça ? ça permettrait à chacun de se concentrer spécifiquement sur une partie et d'argumenter sur les commentaires via PR

**Comment by jferard** [comment]
@khena J'ai manqué ton message. Je suis en relecture (il y a de grosses boulettes !!). J'envoie un PR dès que fini la relecture.

**Comment by jferard** [comment]
Voir PR https://github.com/jeantil/admission_post_bac/pull/30.
Je ferme et on pourra ouvrir des issues pour les différents points qui posent problème.
