### ISSUE TITLE
Renommage des variables

### ISSUE THREAD

**Issue by BuonOmo** [jeantil/admission_post_bac#25]
Si je fais une pull request avec renommage global de toutes les variables ça vous intéresse ? J’utiliserai pour ça les noms qui sont dans le fichier variable.txt, en prenant soin de régler les litiges sur la nomenclature avec vous dans les réponses à cet incident !

**Comment by Sboulahia** [comment]
Non, il vaut mieux laisser le nommage original des variables, cela évitera les quiproquos et nous aidera à comprendre la signification de variables que nous n'avons pas encore comprises.

**Comment by BuonOmo** [comment]
Pas bête, je met en wontfix, peut-être à revoir plus tard une fois que le code sera totalement éclairci pour faciliter la lecture de nouveaux arrivants.
**edit:** bizarrement je n’ai pas accès aux labels, donc impossible de rajouter la motion _wontfix_..

**Comment by AxelVoitier** [comment]
Ca peut etre fait mais dans une copie du fichier d'origine je pense.

**Comment by khena** [comment]
Je clôture pour l'instant, mais il ne faut pas hésiter à faire un fichier séparé je pense. Par contre le refactoring, si c'est pour alléger le code, autant remplacer les where par des jointures quand c'est nécessaire.
