### ISSUE TITLE
Ordre de voeux négatif, vraiment ?

### ISSUE THREAD

**Issue by GuillaumeTara** [jeantil/admission_post_bac#28]
Bonjour,

J'ai lu à plusieurs reprises l'idée que l'ordre des voeux serait négatif et que cela pourrait expliquer pourquoi on met 0 à un voeu qu'on ne veut pas.

Mais cette théorie me paraît étrange... Prenons un cas concret.
X a classé la formation T en voeu 1
Y a classé la formation T en voeu 3
Z n'a pas classé la formation T

L'algo donne donc la valeur 0 au classement de Z
On a donc X = 1, Y = 3, Z = 0.
En toute logique on voudrait
X
Y
Z
Mais les deux cas de figure ne retournent pas ce résultat.
Si on classe tel quel ça donnerait : 
Z = 0
X = 1
Y = 3
Si les voeux sont stockés négativement => X = -1, Y = -3, Z = 0 donc l'odre donne : 
Y = -3
X = -1
Z = 0

Du coup ça me paraît tout aussi bizarre.... Ou peut-être que je pase à côté de quelque chose dans cette idée d'ordre de voeux négatif... Si ça se trouve les voeux sont positifs et autre part dans le code qu'on n'a pas, il y a une fonction qui élimine tous les voeux 0 ?...
Ou alors comme dans tous les cas ils n'ont pas classé le voeu, il ne le leur sera pas proposé et donc d'une manière ou d'une autre ils seront éliminés de la liste ce qui explique qu'ils soient laissés dans la liste à cette étape...

**Comment by AxelVoitier** [comment]
Si ils sont code en negatif il faut logiquement les complementer (ie. -7 + x).
Oui, c'est encore plus etrange. Mais :
- A la base c'est juste une possibilite theorique. Les maths nous disent que c'est possible et on a pas d'element pour confirmer ou infirmer.
- Comme dit dans une autre issue, on ne peut pas faire de supposition sur fonctionnement de l'esprit du developpeur. Certaines personnes arrivent tres bien a raisonner comme cela.
- En plus il semblerai que le developpeur etait une personne partie a la retraite depuis, donc "d'une autre generation" qui n'a pas forcement adoptee les memes styles et les meme manieres de penser que nous. Encore plus quand on sait que nos predecesseurs qui ont connu les debuts de l'informatique ont ete formate par les limitations qui existaient au debut. Pour en avoir connu des developpeurs de cet epoque, il est clair qu'ils ont vraiment des manieres de penser les algos qui nous paraissent bien torturees mais qui souvent donnent des resultats ingenieux.

Et en effet, il existe aussi la possibilite plus simple que ca soit resolu en post traitement. Ce n'est pas a exclure non plus, evidemment.

Il faut accepter qu'on a pas de quoi trouver toutes les reponses, faire avec et considerer toutes les possibilites. C'est soit un bug (un peu gros quand meme, on aurait entendu des histoires la dessus), soit les voeux sont en negatif (et donc complemente), soit y'a un post traitement qui supprime les 0 (ca peut aussi ne pas etre la vrai fonction ;) ).

**Comment by jferard** [comment]
Quelques remarques : 
- si c'est en négatif, ce ne peut pas être effectivement l'opposé du rang du voeu (point de vue du candidat), mais les voeux seraient classés de -N (le plus prioritaire) à -1 (le moins prioritaire). Techniquement, ça peut avoir deux effets : 1) ça permet d'avoir une valeur max qu'on ne va pas artificiellement mettre à 100000, et donc de ne pas dépendre de l'implémentation de NUMBER (8 bits, 16 bits, 32 bits, 64 bits ?) ; 2) ça permet d'ajouter des voeux plus prioritaires sans avoir à renuméroter, ou passer en négatif, mais ça je ne vois pas à quoi ça sert.
- On peut difficilement neutraliser les 0 a posteriori, puisqu'ils obtiennent un rang dans la même boucle sur le curseur que les autres. Reste à savoir si ce n'est pas le rang qu'il faut voir dans l'autre sens : un grand rang serait prioritaire par rapport à un petit (c'est la question de ce qui se passe après cette fonction !) 
- sur les développeurs d'une "autre génération", je pense que c'est le métier qui était différent, plus orienté sur : comment faire avec peu de ressources ? D'où des méthodes parfois originales (comment éviter de faire un appel de fonction parce que ça sollicite la pile, etc.), mais qu'on retrouve dès qu'on s'intéresse aux questions d'algorithmie par exemple.

**Comment by jferard** [comment]
_Erreur dans mon message ci-dessus : l'ordre des voeux ne devrait pas être de -N à -1, car si deux candidats avaient un nombre de voeux différents, celui qui a le plus de voeux serait automatiquement prioritaire sur l'autre._

Précision à partir des documents https://drive.google.com/drive/folders/0B6a96AZlutX9RjRZLWxySjYxUVU : les ordres de voeux `a_ve_ord_vg_rel`, `a_ve_ord_aff`, `a_vg_ord` sont de type `NUMBER(3)`, c'est à dire compris entre -999 et +999 (https://docs.oracle.com/cd/B19306_01/olap.102/b14346/dml_datatypes002.htm).

Si l'ordre des voeux est **positif**, il serait confortable d'accorder la valeur 1000 (au delà du max) pour le critère de tri lorsqu'aucun voeu n'est fait, afin de renvoyer le candidat après les autres, sans risque de conflit avec un éventuel 1000è voeu qui n'aurait jamais pu être inséré dans la DB. 

L'hypothèse de l'ordre en **négatif** ne présente pas cet avantage, puisqu'on peut insérer 1999 voeux en base : premier voeu -> -999, deuxième voeu -> -998, 1000è voeu -> 0 (conflit avec l'absence de voeu), 1001è voeu -> 1 (passe après l'absence de voeu).

Cela va contre l'hypothèse des voeux en négatif, sans pour autant être rédhibitoire !

**Comment by khena** [comment]
Si tout le monde est d'accord, suite au dernier article du site du monde, les voeux ne sont pas négatifs. Je clotûre, n'hésitez pas à le réouvrir si nécessaire

**Comment by Sboulahia** [comment]
Bonjour,
Aujourd'hui sur APB un candidat ne peut pas postuler pour plus de 40 vœux, on est encore loin de l'époque où cette limite sera supérieure à 999.
