### ISSUE TITLE
Schéma UML de certaines tables de la BDD

### ISSUE THREAD

**Issue by GuillaumeTara** [jeantil/admission_post_bac#29]
Hello,

On a reçu ces docs qui correspondraient à des schémas de certaines tables de la base de données. Je n'ai pas encore eu le temps de tout dépioter, du coup je ne sais pas si ça correspond à notre cas de figure, mais j'imagine que ça peut quand même : 

https://drive.google.com/drive/folders/0B6a96AZlutX9RjRZLWxySjYxUVU

**Comment by AxelVoitier** [comment]
Est-ce une source officielle, ou une reconstruction officieuse ?

**Comment by khena** [comment]
Source "officielle" mais récupérée de façon officieuse si j'ai bien compris :)

**Comment by jferard** [comment]
Pas une reconstruction officieuse à partir du PDF, c'est sûr, étant donné le niveau de détail !!

**Comment by jferard** [comment]
Après examen, il y en a à la fois trop et pas assez : une table comme `c_can_grp`, essentielle dans le script, n'est pas présente. D'un autre côté, on a de nombreuses informations qui ne sont pas dans le script (ce qui est légitime s'agissant d'un numéro de tel ou autres données analogues). les champs collent bien à ce que nous avons (pas de différence dans le nommage, etc.). 

A  part ça, ce peut-être un point d'entrée pour comprendre la nomenclature des tables et champs...

**Comment by khena** [comment]
Je plussois @jferard : comme le code, je pense que ce modèle est incomplet (ou mal fait). Il manque des clés étrangères un peu partout. A ne considérer que comme un élément de soutien pour la compréhension.

**Comment by khena** [comment]
J'ajoute au wiki et je clôture.
