### ISSUE TITLE
Réorganisation du repo

### ISSUE THREAD

**Issue by jferard** [jeantil/admission_post_bac#39]
Je pense qu'il faudrait penser à mettre un peu d'ordre dans ce repo : tout est placé dans `src`, alors que la plupart des fichiers n'ont pas vocation à être des sources. Je propose donc une réorganisation comme suit : 

```
src/apb-original.sql <- le plus proche possible du PDF
src/database.sql <- la structure de la base sous format minimal
doc/detail-code/01-declaration_apb_004-044.sql
doc/detail-code/...
doc/detail-code/15-X14-detail-code_apb_387-404.sql
doc/dictionnaire-script.md
doc/variables.txt
doc/documents/Table voeux.pdf <- tous les documents utilisés
doc/documents/...
```

**Comment by khena** [comment]
Entièrement d'accord.

**Comment by khena** [comment]
Je le termine ce soir car c'est chiant à faire depuis l'interface github :p
