### ISSUE TITLE
Lien mort

### ISSUE THREAD

**Issue by lucas34** [jeantil/admission_post_bac#49]
Bonjour,

Le lien vers rue89 dans le ReadMe est mort http://rue89.nouvelobs.com/2016/10/18/voici-code-source-dapb-tenu-secret-jusqua-present-265443

Il semble qu'ils aient changé de nom de domaine vers http://tempsreel.nouvelobs.com/rue89
Je n'arrive pas a retrouver le lien vers l'article.

Lucas

**Comment by khena** [comment]
Merci, je le corrige de  suite, je pense que c'est celui-ci :
http://tempsreel.nouvelobs.com/rue89/rue89-nos-vies-connectees/20161018.RUE4061/voici-le-code-source-d-admission-post-bac-qu-ont-recu-les-lyceens.html
