### ISSUE TITLE
Algorithme.pdf: lien mort

### ISSUE THREAD

**Issue by thomasarmel** [jeantil/admission_post_bac#51]
Hello,
Le lien https://droitsdeslyceens.com/medias/files/algorithme.pdf est mort.
J'ai téléchargé le document sur archive.org en PJ de l'issue, pour éventuellement le mettre directement sur le repo :-)
[algorithme.pdf](https://github.com/jeantil/admission_post_bac/files/14764566/algorithme.pdf)

**Comment by jeantil** [comment]
ca n'a pas grand interet : admission post bac n'est plus utilisé depuis plusieurs années maintenant remplacé par parcoursup dont le code peut etre trouvé la : https://gitlab.mim-libre.fr/parcoursup/algorithmes-de-parcoursup

**Comment by thomasarmel** [comment]
Ok merci pour le lien, je pensais que le code de ParcourSup n'avait pas été rendu public.
Concernant le fichier _algorithme.pdf_ je voyais l'intérêt de le rajouter dans le repo surtout pour l'intérêt "historique".
Merci pour la réponse en tous cas !
